import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Button from "../components/button";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="text-gray-600 body-font bg-black">
        <div className="container px-5 py-24 mx-auto">
          <div className="flex flex-wrap">
            <div className="p-4 md:w-1/3">
              <div className="h-full border-2 border-purple-500 border-opacity-60  overflow-hidden">
                <div className="p-6 text-white ">
                  <h1 className="text-3xl font-medium mb-3">For bookings</h1>
                  <p className="font-thin mb-3  text-sm">
                    Arrange a delivery for your package or enter some of your
                    requirements to get a quick quote and see how our rates
                    compare.
                  </p>
                  <div className="flex items-center flex-wrap ">
                    <Button variant="contained">Instant quote</Button>
                  </div>
                </div>
              </div>
            </div>
            <div className="p-4 md:w-1/3">
              <div className="h-full border-2 border-green-500 border-opacity-60  overflow-hidden">
                <div className="p-6 text-white ">
                  <h1 className="text-3xl font-medium mb-3">For businesses</h1>
                  <p className="font-thin mb-3 text-sm">
                    Find out how we can partner up to provide last-mile delivery
                    solutions that work for you and your customers.
                  </p>
                  <div className="flex items-center flex-wrap">
                    <Button variant="contained">Instant quote</Button>
                  </div>
                </div>
              </div>
            </div>
            <div className="p-4 md:w-1/3">
              <div className="h-full border-2 border-red-500 border-opacity-60  overflow-hidden">
                <div className="p-6 text-white ">
                  <h1 className="text-3xl font-medium mb-3">For couriers</h1>
                  <p className="font-thin mb-3 text-sm">
                    Some of the best couriers work with us because we offer
                    flexible hours, great pay and fair treatment. Apply in just
                    10 minutes.
                  </p>
                  <div className="flex items-center flex-wrap ">
                    <Button variant="contained">Instant quote</Button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default Home;
